# Generated by Django 5.2.5 on 2025-08-14 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestion', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='adresse',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='telephone',
        ),
        migrations.AlterField(
            model_name='patient',
            name='age',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='patient',
            name='nom',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='patient',
            name='prenom',
            field=models.CharField(max_length=50),
        ),
    ]
